# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Install .net core 3.1'
  inputs:
    packageType: 'sdk'
    version: '3.1.100'

- task: DotNetCoreCLI@2
  displayName: '.NET Core - Restore packages'
  inputs:
    command: 'restore'
    projects: './src'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: '.NET Core - Build'
  inputs:
    command: 'build'
    projects: './src'